### ISSUE TITLE
Missing Self-Signed SSL Server supports

### ISSUE THREAD

**Issue by marecar3** [Microsoft/SimpleRestClients#15]
Hi,

As I can see there is no support for self-signed ssl server support ?

Thanks,
M.S.

**Comment by deregtd** [comment]
SimpleRestClients just uses your browser's HTTP stack.  Any issue with self-signed ssl server would be in your browser.

**Comment by marecar3** [comment]
Thanks. However I am using this library for ReactXP project. Can you point to me some other Rest client that I can use ?

**Comment by deregtd** [comment]
We use this library with ReactXP as well -- all it does is use the react native xmlhttprequest shim on that platform.  Any library you use will have the same problem unless they have an entirely different HTTP stack that they use.

**Comment by marecar3** [comment]
Thanks!
