### ISSUE TITLE
Missing samples

### ISSUE THREAD

**Issue by maxperga** [Microsoft/SimpleRestClients#2]
Could you please add a sample about how to use this package? Thanks!

**Comment by ms-deregtd** [comment]
We absolutely intend to in the near future, we're just a bit swamped on time at the moment dealing with the ReactXP and ReSub releases.  We'd like to do a holistic integrated sample with ReactXP, ReSub, NoSqlProvider, and SimpleRestClients; but we don't have any timeline yet. :(

**Comment by kokizzu** [comment]
there are minimal example on https://microsoft.github.io/reactxp/docs/extensions/restclient.html

**Comment by martinnov92** [comment]
@kokizzu @maxperga  I found that minimal example useless to be fair 😆 I was trying to do it just like it is in the example, but all I got was errors. For me the easiest way was to do this:

```
        const { GenericRestClient } = require('../SimpleRestClients/src/GenericRestClient');
        const headers = {...};
        const fetch = new GenericRestClient('http://***.***.***.***/');
        fetch.performApiPost('login', user,headers).then((res: any) => console.log(res));
```

And why this is not on the npm? Thanks

**Comment by ms-deregtd** [comment]
While you can use it that way, you don't get any real power of GenericRestClient.  The sample up at the reactxp docs is a much better example to follow, since it shows how you can add authentication headers, helper methods, etc.  What errors were you getting trying to use it that way?

Someday we'll have time to get a more official example going, but somehow there's always more important fish to fry...

**Comment by shameister** [comment]
Please bring the imports from this example https://github.com/Microsoft/SimpleRestClients to this page: https://microsoft.github.io/reactxp/docs/extensions/restclient.html

It feels like being left in the rain, if having an incomplete example, which shows errors.

Additionally it would be nice, if you would add the export-statement in the examples, so they can be used without the hassle to get them working.

![bildschirmfoto 2018-06-12 um 16 45 49](https://user-images.githubusercontent.com/98413/41297786-357e38c4-6e60-11e8-9d6e-eab2d2d2b18b.png)

**Comment by berickson1** [comment]
Opened https://github.com/Microsoft/reactxp/pull/972
